### Get all tours
http://localhost:3000/api/v1/tours

### Get tour(by parameter)
http://localhost:3000/api/v1/tours/6447983c1861db33b84c4251


### Create new tour
POST http://localhost:3000/api/v1/tours HTTP/1.1
content-type: application/json

{
  "name":"Secret Tour",
  "description":"Just test",
  "duration":1,
  "maxGroupSize":1,
  "difficulty":"difficult",
  "price":1,
  "summary":"Test tour",
  "imageCover":"tour-test-cover.svg",
  "secretTour":true
}

### Update tour
PATCH http://localhost:3000/api/v1/tours/6447983c1861db33b84c4250 HTTP/1.1
content-type: application/json

{
  "ratingsAverage": 4.9
}

### Delete tour
DELETE http://localhost:3000/api/v1/tours/8 HTTP/1.1

### Sorting
http://localhost:3000/api/v1/tours?sort=-price,-ratingsAverage

### Limiting
http://localhost:3000/api/v1/tours?fields=name,duration,price

### Pagination
http://localhost:3000/api/v1/tours?limit=3&page=3&fields=name

### Alias(get top 5 cheap tours
http://localhost:3000/api/v1/tours/top-5-cheap

### Aggregation Pipeline:tour states
http://localhost:3000/api/v1/tours/tour-stats

### Aggregation Pipeline:monthly plan
http://localhost:3000/api/v1/tours/monthly-plan/2021

